### ISSUE TITLE
Image name fingerprinting

### ISSUE THREAD

**Issue by pedrokost** [kubenstein/middleman-simple-thumbnailer#10]
This extension does not seem to work with [`activate :asset_hash`](https://middlemanapp.com/advanced/improving_cacheability/). The generated file names do not have a hash at the end.
Example:

```
<%= image_tag 'submission_results.png', class:"img-circle", alt:"One click to download your results", resize_to: '200x200' %>
```
generates:
```
<img class="img-circle" alt="One click to download your results" src="images/submission_results.200x200.png">
```

while omitting `resize_to`:

```
<%= image_tag 'submission_results.png', class:"img-circle", alt:"One click to download your results" %>
```
generates:
```
<img class="img-circle" alt="One click to download your results" src="images/submission_results-b2ceca59.png">
```

I would expect to get this:
```
<img class="img-circle" alt="One click to download your results" src="images/submission_results.200x200-b2ceca59.png">
```

**Comment by kubenstein** [comment]
hi @pedrokost, thank you for pointing this out. i checked and in deed images dont get hash at the end. Will investigate this issue and propose some solution as soon as possible.

**Comment by kubenstein** [comment]
hi i spent some time investigating this issue. looks like assets hashing takes place before pages generation but our thumbs are generated during this process. thats why thumbnails dont have hashes. Unfortunately for now i wasnt able to find workaround to rehash everything once again.
i think other extensions like e.g. [middleman-automatic-clowncar](https://github.com/Octo-Labs/middleman-automatic-clowncar) may have solved this problem. will check them for clues.

**Comment by ymph** [comment]
Hello,

Asset hashing is using the sitemap and the file themselves to generate the hash. Therefore extension that do not modify the sitemap like simple thumbnailer can not be taken into account by asset hashing.
In our case, even if we changed the sitemap when we generate the images (in the template helper or in the after build callback), this is too late.The sitemap must fixed before the page are rendered.

Extensions like [middleman-automatic-clowncar](https://github.com/Octo-Labs/middleman-automatic-clowncar) process all files in a given directory. They do it either during initialization, either during the `manipulate_resource_list` callback. In any case, they know in advance (of the rendering) what file they must process.

So as a conclusion, without a radical architecture change in simple thumbnailer, I do not think this bug can be corrected. If we find a way to make this extension work like all others, i.e. correctly adding the new resized images in the sitemap, this problem will be naturally solved.

I suggest to close this issue, but to open a new one where we could discuss about re-achitecturing  the extension.

Regards,

ymh

PS: the discussion thread of the PR [#12 (Support middleman v4.1)](https://github.com/kubenstein/middleman-simple-thumbnailer/pull/12) is revelant to this issue.

**Comment by ymph** [comment]
Hello,

I close this issue because I do not think it can be corrected with the current architecture, and it will be automatically corrected if we implement a new architecture as described in issue #13.

Regards,

ymh
