### ISSUE TITLE
resized images aren't being added to the resource manifest

### ISSUE THREAD

**Issue by simmerz** [kubenstein/middleman-simple-thumbnailer#18]
I'm using middleman-s3_sync to upload files to S3. The resized versions of the images aren't being added to the resource manifest, so they don't get uploaded, breaking the site.

**Comment by ymph** [comment]
Hello,

Is that a new problem on an project using middleman-simple-thumbnailer since a long time , or is this the description of a problem you encountered when trying to use middleman-simple-thumbnailer for the first time ?

Thank you,

ymh

**Comment by simmerz** [comment]
Trying to use the extension for the first time.

**Comment by ymph** [comment]
Hello,

Thank you for your response.

Unfortunately, this is a direct consequence of the current implementation and is not easily corrected. This is explained in the issue #13.

The only solutions I came up for the moment will imply a radical change in the way this extension is used, which can be problematic for existing users. So do not expect a correction in a near future.

In the meantime I will update the documentation to warn of this limitation. When done I will close this issue as duplicate of #13.

Regards,

ymh

**Comment by ymph** [comment]
Duplicate of issue #13.
