### ISSUE TITLE
crash because MiddlemanSimpleThumbnailer::Rack (NameError)

### ISSUE THREAD

**Issue by raumi75** [kubenstein/middleman-simple-thumbnailer#23]
When I run 1.3.0 I get this error when I run middleman build:

`.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/middleman-simple-thumbnailer-1.3.0/lib/middleman-simple-thumbnailer/extension.rb:34:in after_configuration': uninitialized constant MiddlemanSimpleThumbnailer::Rack (NameError)`

**Comment by ymph** [comment]
Hello,

This seems to be due to an error when I built and pushed the gem to rubygems.org.
I published a new version 1.3.1 and yanked the 1.3.0.

Can you please try it to see if this is ok now ?

Thank you.

**Comment by raumi75** [comment]
Thank you very much. That fixed it for me.
