### ISSUE TITLE
Special characters in resized_image_name

### ISSUE THREAD

**Issue by zdenekdrahos** [kubenstein/middleman-simple-thumbnailer#4]
[resize](http://www.graphicsmagick.org/GraphicsMagick.html#details-resize) can contain special characters `%, @, !, <, >`. Some of them are reserved characters in [URI](http://stackoverflow.com/a/1547940), furthermore `<, >` is not allowed in Windows filename. I think it would be safer to filter these characters in [resized_image_name](https://github.com/kubenstein/middleman-simple-thumbnailer/blob/master/lib/middleman-simple-thumbnailer/image.rb#L50):

```
.gsub!(/[%@!<>]/, '')
```

**Comment by kubenstein** [comment]
yes thats good idea to filter those out. will add this today. thx.

**Comment by kubenstein** [comment]
One thing i noticed, sometimes i use `<` and `>` to describe behaviour in which image should be resized. for example: `= image_tag image, resize_to: '150x150>'` and the `>` becomes part of file name after. I think completely gsubing may not be good idea. Maybe change to something like `gt` or `lt`? what do you think?

**Comment by zdenekdrahos** [comment]
I agree, encoding is better approach.

**Comment by kubenstein** [comment]
added in 6eeb319e766687064d3eb126a8a2508eb306ef47 commit. already merged into master.
